### ISSUE TITLE
Not being able to see spell's? (1.16.3)

### ISSUE THREAD

**Issue by ProfEnd** [RobertSkalko/Age-of-Exile#39]
In most cases, the spells won't show the projectile shot or part of the spell thrown.
Mod being used alongside other mods, will give modlist if needed.

**Comment by RobertSkalko** [comment]
What's your mod version? This happened to a few people on old versions.

**Comment by ProfEnd** [comment]
Age-Of-Exile-1.16.3-1.7.6 is the file name, so I assume the version is 1.7.6

**Comment by RobertSkalko** [comment]
post a full log

**Comment by hagfelsh** [comment]
I also have this problem both in singleplayer and server.  Changing particle settings and graphics level in the client make no difference.

mc version: **1.16.3**
fabric version: **0.6.1.51**
age of empires version: **1.16.3-1.7.6**

mod config paste here: https://pastebin.com/zFB2HvdJ
server log here: https://pastebin.com/qgcEZSus

**Comment by RobertSkalko** [comment]
Remove immersive portals.

**Comment by hagfelsh** [comment]
Remarkable, that fixed it exactly as predicted.  How could you tell that was the problem?!

**Comment by RobertSkalko** [comment]
Because spells being invisible can only happen if you join a server with a different mod version or if you're using immersive portals, which always has problems with my mod. I did not find other similar bugs yet. So far the only 2 mods that cause big problems with mine are immersive portals and optifine/optifabric, and they tend to cause problems with all other mods.
I will add a chat on login warning in next update if you have that mod installed. I don't want to flat out put it as incompatible as the fabric's error messaging is really confusing.
