### ISSUE TITLE
Fire Mage Entity Ticking causing the server to crash

### ISSUE THREAD

**Issue by faustojc** [RobertSkalko/Age-of-Exile#56]
Spawning of Fire Mage entity makes my Aternos server to crash. I kept killing that specific entity to stop my server from crashing but still it keeps spawning naturally. 

Crash log:
[Crash Log.txt](https://github.com/RobertSkalko/Age-of-Exile/files/5941876/Crash.Log.txt)

**Comment by RobertSkalko** [comment]
Closing all bug related issues as I just pushed a big update. (many changes to the code)
If the issue is still there, please create a new issue and provide new log files.

The 1.8 update is currently BETA which means it's not ready for stable worlds. If you are playing multiplayer I suggest you wait for a release candidate.
